/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.x-dev
 * Generated at: 2024-11-17 08:48:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AdminPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #f8f9fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar {\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("	width: 15vw;\r\n");
      out.write("	position: relatvie;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	background-color: #343a40;\r\n");
      out.write("	padding-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a {\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a:focus {\r\n");
      out.write("	color: white;\r\n");
      out.write("	background-color: #0000FF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a:hover {\r\n");
      out.write("	color: white;\r\n");
      out.write("	background-color: #495057;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content {\r\n");
      out.write("	margin-left: 200px; /* Width of the sidebar */\r\n");
      out.write("	width: 85vw;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	right: 0;\r\n");
      out.write("	float: right;\r\n");
      out.write("	max-height: 100vh;\r\n");
      out.write("	overflow: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".username {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 20px;\r\n");
      out.write("	right: 20px;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	color: #343a40;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-group {\r\n");
      out.write("	width: 20vw;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-nav {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	height: 5vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-btn {\r\n");
      out.write("	height: 80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logout-div {\r\n");
      out.write("	width: 25vw;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-item {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	border-bottom: 1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"fetchOrders()\">\r\n");
      out.write("	<div class=\"sidebar\">\r\n");
      out.write("		<h5 class=\"text-center text-white\">Welcome, admin</h5>\r\n");
      out.write("		<ul class=\"nav flex-column\">\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("				onclick=\"fetchOrders(event)\">Orders</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("				onclick=\"fetchPendingOrders(event)\">Pending Order</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("				onclick=\"fetchCanceledOrders(event)\">Cancelled Order</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("				onclick=\"fetchCompletedOrders(event)\">Delivered Order</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("				onclick=\"fetchCustomers(event)\">customers</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("				onclick=\"fetchCancelReason(event)\"> Cancel reason</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("				onclick=\"fetchProducts(event)\">products </a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("				onclick=\"fetchProductCategory(event)\"> Products category</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("				onclick=\"fetchCustomerWithoutOrder(event)\">customers without\r\n");
      out.write("					order</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("				onclick=\"fetchPayments(event)\">payments</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"content\">\r\n");
      out.write("		<div class=\"top-nav\">\r\n");
      out.write("			<div class=\"container mt-5\">\r\n");
      out.write("				<button class=\"btn btn-primary\" data-toggle=\"modal\"\r\n");
      out.write("					data-target=\"#makeAdminModal\">Make Admin</button>\r\n");
      out.write("				<button class=\"btn btn-primary\" data-toggle=\"modal\"\r\n");
      out.write("					data-target=\"#deliveredModal\">Delivered</button>\r\n");
      out.write("				<button class=\"btn btn-primary\" data-toggle=\"modal\"\r\n");
      out.write("					data-target=\"#addProductModal\">Add Product</button>\r\n");
      out.write("				<button class=\"btn btn-primary\" data-toggle=\"modal\"\r\n");
      out.write("					data-target=\"#addCategoryModal\">Add Category</button>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"logout-div\">\r\n");
      out.write("				<button class=\"btn btn-secondary\" data-bs-toggle=\"modal\"\r\n");
      out.write("					data-bs-target=\"#changePasswordModal\">Change password</button>\r\n");
      out.write("				<form method=\"post\" action=\"logout\">\r\n");
      out.write("					<input type=\"hidden\" name=\"action\" value=\"logout\">\r\n");
      out.write("					<button type=\"submit\" class=\"btn btn-danger\">Logout</button>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container mt-5\">\r\n");
      out.write("			<table class=\"table table-bordered\" id=\"write_container\">\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"makeAdminModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"makeAdminModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"makeAdminModalLabel\">Make Admin</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span>&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<p>Enter the user ID to make them an admin:</p>\r\n");
      out.write("					<input type=\"number\" class=\"form-control\" id=\"userIdInput\"\r\n");
      out.write("						placeholder=\"User ID\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-dismiss=\"modal\">Close</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"\r\n");
      out.write("						onclick=\"makeAdmin()\">Submit</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal increase stock -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"increaseStockModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"increaseStockModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"increaseStockModalLabel\">Increase\r\n");
      out.write("						Stock</h5>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<form id=\"increaseStockForm\" onsubmit=\"return validateStock(event)\">\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"stockQuantity\" class=\"form-label\">Stock\r\n");
      out.write("								Quantity</label> <input type=\"number\" class=\"form-control\"\r\n");
      out.write("								id=\"stockQuantity\" min=\"1\" required>\r\n");
      out.write("							<div class=\"invalid-feedback\">Please enter a quantity\r\n");
      out.write("								greater than 0.</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-success\">Submit</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Confirm Delivery Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"deliveredModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"deliveredModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"deliveredModalLabel\">Confirm\r\n");
      out.write("						Delivery</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span>&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<p>Enter the order ID to confirm delivery:</p>\r\n");
      out.write("					<input type=\"number\" class=\"form-control\" id=\"orderIdInput\"\r\n");
      out.write("						placeholder=\"Order ID\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-dismiss=\"modal\">Close</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-success\" data-dismiss=\"modal\"\r\n");
      out.write("						onclick=\"confirmDelivery()\">Submit</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Change Password Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"changePasswordModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"changePasswordModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"changePasswordModalLabel\">Change\r\n");
      out.write("						Password</h5>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<form id=\"changePasswordForm\"\r\n");
      out.write("						onsubmit=\"handleChangePassword(event)\">\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"newPassword\" class=\"form-label\">Old Password</label>\r\n");
      out.write("							<input type=\"password\" class=\"form-control\" id=\"oldPassword\"\r\n");
      out.write("								required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"newPassword\" class=\"form-label\">New Password</label>\r\n");
      out.write("							<input type=\"password\" class=\"form-control\" id=\"newPassword\"\r\n");
      out.write("								required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\"\r\n");
      out.write("							data-bs-dismiss=\"modal\">Submit</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Add Product Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"addProductModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"addProductModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"addProductModalLabel\">Add Product</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span>&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<p>Enter product details:</p>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"productName\">Product Name</label> <input type=\"text\"\r\n");
      out.write("							class=\"form-control\" id=\"productName\" placeholder=\"Product Name\"\r\n");
      out.write("							required>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"productDescription\">Product Description</label>\r\n");
      out.write("						<textarea class=\"form-control\" id=\"productDescription\"\r\n");
      out.write("							placeholder=\"Product Description\" required></textarea>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"productPrice\">Price</label> <input type=\"number\"\r\n");
      out.write("							step=\"0.01\" class=\"form-control\" id=\"productPrice\"\r\n");
      out.write("							placeholder=\"Price\" required>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"productQuantity\">Quantity</label> <input type=\"number\"\r\n");
      out.write("							class=\"form-control\" id=\"productQuantity\" placeholder=\"Quantity\"\r\n");
      out.write("							required>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"categoryId\">Category ID</label> <input type=\"number\"\r\n");
      out.write("							class=\"form-control\" id=\"categoryId\" placeholder=\"Category ID\"\r\n");
      out.write("							required>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-dismiss=\"modal\">Close</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-info\" onclick=\"addProduct()\">Submit</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Add Category Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"addCategoryModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"addCategoryModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"addCategoryModalLabel\">Add\r\n");
      out.write("						Category</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span>&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<p>Enter category name:</p>\r\n");
      out.write("					<input type=\"text\" class=\"form-control\" id=\"categoryName\"\r\n");
      out.write("						placeholder=\"Category Name\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-dismiss=\"modal\">Close</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-warning\"\r\n");
      out.write("						onclick=\"addCategory()\">Submit</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		function makeAdmin() {\r\n");
      out.write("			const userId = document.getElementById(\"userIdInput\").value;\r\n");
      out.write("			if (!userId) {\r\n");
      out.write("				alert(\"Please enter a valid User ID.\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"POST\", \"validator?action=changeRoleToAdmin&userId=\"\r\n");
      out.write("					+ userId, true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					alert(xhr.responseText);\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("			$('#makeAdminModal').modal('hide');\r\n");
      out.write("\r\n");
      out.write("			document.getElementById(\"userIdInput\").value = '';\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function openStock(button) {\r\n");
      out.write("			currentButton = button;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function validateStock(event) {\r\n");
      out.write("			event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("			const stockQuantity = document.getElementById('stockQuantity').value;\r\n");
      out.write("			const productId = currentButton.getAttribute('data-product-id');\r\n");
      out.write("			console.log(productId);\r\n");
      out.write("			if (stockQuantity <= 0) {\r\n");
      out.write("				alert(\"stock quantity can't be less than 1\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"GET\", \"products?action=update_stock&productId=\"\r\n");
      out.write("					+ productId + \"&quantity=\" + stockQuantity, true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					alert(xhr.responseText);\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("\r\n");
      out.write("			const modal = bootstrap.Modal.getInstance(document\r\n");
      out.write("					.getElementById('increaseStockModal'));\r\n");
      out.write("			modal.hide();\r\n");
      out.write("\r\n");
      out.write("			return true;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function confirmDelivery() {\r\n");
      out.write("			const orderId = document.getElementById(\"orderIdInput\").value;\r\n");
      out.write("\r\n");
      out.write("			if (!orderId) {\r\n");
      out.write("				alert(\"Please enter a valid Order ID.\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"POST\",\r\n");
      out.write("					\"order_tables_praveen?action=make_delivered&orderId=\"\r\n");
      out.write("							+ orderId, true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					alert(xhr.responseText);\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("\r\n");
      out.write("			$('#deliveredModal').modal('hide');\r\n");
      out.write("\r\n");
      out.write("			document.getElementById(\"orderIdInput\").value = '';\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function addProduct() {\r\n");
      out.write("			const productName = document.getElementById(\"productName\").value\r\n");
      out.write("					.trim();\r\n");
      out.write("			const productDescription = document\r\n");
      out.write("					.getElementById(\"productDescription\").value.trim();\r\n");
      out.write("			const productPrice = document.getElementById(\"productPrice\").value;\r\n");
      out.write("			const productQuantity = document.getElementById(\"productQuantity\").value;\r\n");
      out.write("			const categoryId = document.getElementById(\"categoryId\").value;\r\n");
      out.write("\r\n");
      out.write("			if (!productName || !productDescription || !productPrice\r\n");
      out.write("					|| !productQuantity || !categoryId) {\r\n");
      out.write("				alert(\"Please fill in all fields.\");\r\n");
      out.write("				return;\r\n");
      out.write("			} else if (productQuantity < 0) {\r\n");
      out.write("				alert(\"quantity can't be less than 0\");\r\n");
      out.write("				return;\r\n");
      out.write("			} else if (productPrice < 0) {\r\n");
      out.write("				alert(\"price can't be less than 0\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"POST\", \"products?action=add_product&productName=\"\r\n");
      out.write("					+ productName + \"&productDescription=\" + productDescription\r\n");
      out.write("					+ \"&productPrice=\" + productPrice + \"&productQuantity=\"\r\n");
      out.write("					+ productQuantity + \"&categoryId=\" + categoryId, true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					alert(\"Successfully added\");\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("\r\n");
      out.write("			$('#addProductModal').modal('hide');\r\n");
      out.write("			document.getElementById(\"productName\").value = '';\r\n");
      out.write("			document.getElementById(\"productDescription\").value = '';\r\n");
      out.write("			document.getElementById(\"productPrice\").value = '';\r\n");
      out.write("			document.getElementById(\"productQuantity\").value = '';\r\n");
      out.write("			document.getElementById(\"categoryId\").value = '';\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function addCategory() {\r\n");
      out.write("			const categoryName = document.getElementById(\"categoryName\").value\r\n");
      out.write("					.trim();\r\n");
      out.write("\r\n");
      out.write("			if (!categoryName) {\r\n");
      out.write("				alert(\"Please enter a valid category name.\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"POST\",\r\n");
      out.write("					\"product_category_controller?action=add_category&categoryName=\"\r\n");
      out.write("							+ categoryName, true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					alert(\"Successfully added\");\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("\r\n");
      out.write("			$('#addCategoryModal').modal('hide');\r\n");
      out.write("			document.getElementById(\"categoryName\").value = '';\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function handleChangePassword(event) {\r\n");
      out.write("			event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("			const newPassword = document.getElementById('newPassword').value\r\n");
      out.write("					.trim();\r\n");
      out.write("			const oldPassword = document.getElementById('oldPassword').value\r\n");
      out.write("					.trim();\r\n");
      out.write("\r\n");
      out.write("			if (!newPassword || !oldPassword) {\r\n");
      out.write("				alert(\"Please fill all fields\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z]).{8,}$/;\r\n");
      out.write("			if (!passwordRegex.test(newPassword)\r\n");
      out.write("					|| !passwordRegex.test(oldPassword)) {\r\n");
      out.write("				alert(\"Password must be at least 8 characters long, with at least one lowercase and one uppercase letter.\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"POST\", \"validator?action=change_password&newPassword=\"\r\n");
      out.write("					+ newPassword + \"&oldPassword=\" + oldPassword, true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					alert(xhr.responseText);\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("\r\n");
      out.write("			document.getElementById(\"newPassword\").value = '';\r\n");
      out.write("			document.getElementById(\"oldPassword\").value = '';\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function removeProduct(button) {//TODO\r\n");
      out.write("			console.log(\"remove product dread \"+button.dataset.productId);\r\n");
      out.write("			const row = button.closest('tr');\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"GET\", \"products?action=remove_product&product_id=\"\r\n");
      out.write("					+ button.dataset.productId, true);\r\n");
      out.write("\r\n");
      out.write("			xhr.send();\r\n");
      out.write("			const productId = row.dataset.productId;\r\n");
      out.write("\r\n");
      out.write("			row.remove();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function fetchOrders(event) {\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"GET\", \"order_tables_praveen?action=get_all_orders\", true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					document.getElementById(\"write_container\").innerHTML = xhr.responseText;\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function fetchPendingOrders(event) {\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr\r\n");
      out.write("					.open(\r\n");
      out.write("							\"GET\",\r\n");
      out.write("							\"order_tables_praveen?action=get_orders_by_status&status=pending\",\r\n");
      out.write("							true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					document.getElementById(\"write_container\").innerHTML = xhr.responseText;\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function fetchCanceledOrders(event) {\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr\r\n");
      out.write("					.open(\r\n");
      out.write("							\"GET\",\r\n");
      out.write("							\"order_tables_praveen?action=get_orders_by_status&status=canceled\",\r\n");
      out.write("							true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					document.getElementById(\"write_container\").innerHTML = xhr.responseText;\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function fetchCompletedOrders(event) {\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr\r\n");
      out.write("					.open(\r\n");
      out.write("							\"GET\",\r\n");
      out.write("							\"order_tables_praveen?action=get_orders_by_status&status=completed\",\r\n");
      out.write("							true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					document.getElementById(\"write_container\").innerHTML = xhr.responseText;\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function fetchCustomers(event) {\r\n");
      out.write("			console.log(\"dfcus\");\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"GET\", \"validator?action=get_customers\", true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					document.getElementById(\"write_container\").innerHTML = xhr.responseText;\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function fetchCancelReason(event) {\r\n");
      out.write("			console.log(\"dread\");\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr\r\n");
      out.write("					.open(\"GET\", \"cancel_controller?action=get_cancel_records\",\r\n");
      out.write("							true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					document.getElementById(\"write_container\").innerHTML = xhr.responseText;\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function fetchProducts(event) {\r\n");
      out.write("			console.log(\"dread\");\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"GET\", \"products?action=get_product_records\", true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					document.getElementById(\"write_container\").innerHTML = xhr.responseText;\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function fetchProductCategory(event) {\r\n");
      out.write("			console.log(\"dread\");\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"GET\",\r\n");
      out.write("					\"product_category_controller?action=get_product_category\",\r\n");
      out.write("					true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					document.getElementById(\"write_container\").innerHTML = xhr.responseText;\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function fetchCustomerWithoutOrder(event) {\r\n");
      out.write("			console.log(\"dread\");\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"GET\", \"validator?action=get_customers_without_order\",\r\n");
      out.write("					true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					document.getElementById(\"write_container\").innerHTML = xhr.responseText;\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function fetchPayments(event) {\r\n");
      out.write("			console.log(\"dread\");\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"GET\", \"payments?action=get_payments\", true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					document.getElementById(\"write_container\").innerHTML = xhr.responseText;\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
