/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.x-dev
 * Generated at: 2024-11-16 08:18:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.http.HttpSession;

public final class LandingPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	HttpSession sessions = request.getSession(false);
	System.out.println("dfdfd");
	if (sessions == null || sessions.getAttribute("user") == null) {
		response.sendRedirect("LoginPage.jsp");
		return;
	}

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #f8f9fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar {\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("	width: 15vw;\r\n");
      out.write("	position: relatvie;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	background-color: #343a40;\r\n");
      out.write("	padding-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a {\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a:hover {\r\n");
      out.write("	color: white;\r\n");
      out.write("	background-color: #495057;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content {\r\n");
      out.write("	margin-left: 200px; /* Width of the sidebar */\r\n");
      out.write("	width: 85vw;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	right: 0;\r\n");
      out.write("	float: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".username {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 20px;\r\n");
      out.write("	right: 20px;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	color: #343a40;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-group {\r\n");
      out.write("	width: 20vw;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-nav {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-btn {\r\n");
      out.write("	height: 80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-item {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	border-bottom: 1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".delete-button {\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	color: red;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logout-div {\r\n");
      out.write("	width: 28vw;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-icon {\r\n");
      out.write("	font-size: 2rem;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	color: #007bff;\r\n");
      out.write("	top: 24%;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edit-icon {\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	color: #28a745;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-body input {\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"create_cart();fetchAllProducts();\">\r\n");
      out.write("	<div class=\"sidebar\">\r\n");
      out.write("		<h5 class=\"text-center text-white\">Welcome</h5>\r\n");
      out.write("		<ul class=\"nav flex-column\">\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link active\" href=\"#\">Home</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"CancelOrder.jsp\">Cancel\r\n");
      out.write("					order</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("				href=\"ViewOrderPage.jsp\">Order History</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("				href=\"PartialCancel.jsp\">Partial cancel</a></li>\r\n");
      out.write("\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"content\">\r\n");
      out.write("		<div class=\"top-nav\">\r\n");
      out.write("			<form onsubmit=\"fetchProducts(event)\" id=\"productForm\">\r\n");
      out.write("				<div class=\"input-group mb-3\">\r\n");
      out.write("					<input type=\"hidden\" name=\"action\" value=\"search\"> <input\r\n");
      out.write("						type=\"text\" class=\"form-control search-input\" name=\"query\"\r\n");
      out.write("						placeholder=\"Search... laptop, shoe, chair\" aria-label=\"Search\"\r\n");
      out.write("						aria-describedby=\"button-search\" required>\r\n");
      out.write("					<button class=\"btn btn-primary\" type=\"submit\" id=\"button-search\">Search</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"logout-div\">\r\n");
      out.write("				<form method=\"post\" action=\"logout\">\r\n");
      out.write("					<input type=\"hidden\" name=\"action\" value=\"logout\">\r\n");
      out.write("					<button type=\"submit\" class=\"btn btn-danger\">Logout</button>\r\n");
      out.write("				</form>\r\n");
      out.write("				<button class=\"btn btn-secondary\" data-bs-toggle=\"modal\"\r\n");
      out.write("					data-bs-target=\"#changePasswordModal\">Change password</button>\r\n");
      out.write("				<div class=\"mt-5\" onclick=\"updateProfileDate()\">\r\n");
      out.write("					<i class=\"bi bi-person-circle profile-icon\" data-bs-toggle=\"modal\"\r\n");
      out.write("						data-bs-target=\"#profileModal\" ></i>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Button to trigger the cart modal -->\r\n");
      out.write("				<form onsubmit=\"fetchCartItems(event)\" id=\"cart_form\">\r\n");
      out.write("					<input type=\"hidden\" name=\"action\" value=\"view_cart_item\">\r\n");
      out.write("					<button class=\"btn btn-primary cart-btn\" data-bs-toggle=\"modal\"\r\n");
      out.write("						data-bs-target=\"#cartModal\">\r\n");
      out.write("						<i class=\"bi bi-cart\"></i> Cart\r\n");
      out.write("					</button>\r\n");
      out.write("				</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<!-- Cart Modal -->\r\n");
      out.write("				<div class=\"modal fade\" id=\"cartModal\" tabindex=\"-1\"\r\n");
      out.write("					aria-labelledby=\"cartModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("					<div class=\"modal-dialog\">\r\n");
      out.write("						<div class=\"modal-content\">\r\n");
      out.write("							<div class=\"modal-header\">\r\n");
      out.write("								<h5 class=\"modal-title\" id=\"cartModalLabel\">Your Cart</h5>\r\n");
      out.write("								<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("									aria-label=\"Close\"></button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"modal-body\">\r\n");
      out.write("								<ul class=\"list-group\" id=\"cart_item_container\">\r\n");
      out.write("									<!-- Cart items will be dynamically inserted here -->\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"modal-footer\">\r\n");
      out.write("								<div class=\"form-check\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\"\r\n");
      out.write("										name=\"paymentMethod_checkout\" id=\"upi\" value=\"UPI\" checked>\r\n");
      out.write("									<label class=\"form-check-label\" for=\"upi\">UPI</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-check\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\"\r\n");
      out.write("										name=\"paymentMethod_checkout\" id=\"cod\" value=\"COD\"> <label\r\n");
      out.write("										class=\"form-check-label\" for=\"cod\">Cash on Delivery</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								<form id=\"clear_cart_form\" onsubmit=\"clearCart(event)\">\r\n");
      out.write("									<input type=\"hidden\" name=\"action\" value=\"clear_cart_items\">\r\n");
      out.write("									<button class=\"btn btn-secondary\" type=\"submit\">Clear</button>\r\n");
      out.write("								</form>\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("									data-bs-dismiss=\"modal\" onclick=\"checkout(event)\">Checkout</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"modal fade\" id=\"profileModal\" tabindex=\"-1\"\r\n");
      out.write("					aria-labelledby=\"profileModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("					<div class=\"modal-dialog\">\r\n");
      out.write("						<div class=\"modal-content\">\r\n");
      out.write("							<div class=\"modal-header\">\r\n");
      out.write("								<h5 class=\"modal-title\" id=\"profileModalLabel\">Edit Profile</h5>\r\n");
      out.write("								<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("									aria-label=\"Close\"></button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"modal-body\">\r\n");
      out.write("								<!-- Name Field -->\r\n");
      out.write("								<div class=\"mb-3\">\r\n");
      out.write("									<label for=\"name\" class=\"form-label\">Name</label>\r\n");
      out.write("									<div class=\"d-flex justify-content-between\">\r\n");
      out.write("										<input type=\"text\" class=\"form-control\" id=\"name\"\r\n");
      out.write("											value=\"John Doe\" disabled> <i\r\n");
      out.write("											class=\"bi bi-pencil-square edit-icon\"\r\n");
      out.write("											onclick=\"editField('name')\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								\r\n");
      out.write("\r\n");
      out.write("								<!-- Address Field -->\r\n");
      out.write("								<div class=\"mb-3\">\r\n");
      out.write("									<label for=\"state\" class=\"form-label\">Address</label>\r\n");
      out.write("									<div class=\"d-flex justify-content-between\">\r\n");
      out.write("										<input type=\"text\" class=\"form-control\" id=\"address\"\r\n");
      out.write("											value=\"sample value\" disabled> <i\r\n");
      out.write("											class=\"bi bi-pencil-square edit-icon\"\r\n");
      out.write("											onclick=\"editField('address')\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<!-- State Field -->\r\n");
      out.write("								<div class=\"mb-3\">\r\n");
      out.write("									<label for=\"state\" class=\"form-label\">State</label>\r\n");
      out.write("									<div class=\"d-flex justify-content-between\">\r\n");
      out.write("										<input type=\"text\" class=\"form-control\" id=\"state\"\r\n");
      out.write("											value=\"California\" disabled> <i\r\n");
      out.write("											class=\"bi bi-pencil-square edit-icon\"\r\n");
      out.write("											onclick=\"editField('state')\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<!-- City Field -->\r\n");
      out.write("								<div class=\"mb-3\">\r\n");
      out.write("									<label for=\"city\" class=\"form-label\">City</label>\r\n");
      out.write("									<div class=\"d-flex justify-content-between\">\r\n");
      out.write("										<input type=\"text\" class=\"form-control\" id=\"city\"\r\n");
      out.write("											value=\"Los Angeles\" disabled> <i\r\n");
      out.write("											class=\"bi bi-pencil-square edit-icon\"\r\n");
      out.write("											onclick=\"editField('city')\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<!-- Country Field -->\r\n");
      out.write("								<div class=\"mb-3\">\r\n");
      out.write("									<label for=\"country\" class=\"form-label\">Country</label>\r\n");
      out.write("									<div class=\"d-flex justify-content-between\">\r\n");
      out.write("										<input type=\"text\" class=\"form-control\" id=\"country\"\r\n");
      out.write("											value=\"USA\" disabled> <i\r\n");
      out.write("											class=\"bi bi-pencil-square edit-icon\"\r\n");
      out.write("											onclick=\"editField('country')\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<!-- Hint Field -->\r\n");
      out.write("								<div class=\"mb-3\">\r\n");
      out.write("									<label for=\"hint\" class=\"form-label\">Hint</label>\r\n");
      out.write("									<div class=\"d-flex justify-content-between\">\r\n");
      out.write("										<input type=\"text\" class=\"form-control\" id=\"hint\"\r\n");
      out.write("											value=\"My first pet's name\" disabled> <i\r\n");
      out.write("											class=\"bi bi-pencil-square edit-icon\"\r\n");
      out.write("											onclick=\"editField('hint')\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<!-- Pincode Field -->\r\n");
      out.write("								<div class=\"mb-3\">\r\n");
      out.write("									<label for=\"pincode\" class=\"form-label\">Pincode</label>\r\n");
      out.write("									<div class=\"d-flex justify-content-between\">\r\n");
      out.write("										<input type=\"text\" class=\"form-control\" id=\"pincode\"\r\n");
      out.write("											value=\"90001\" disabled> <i\r\n");
      out.write("											class=\"bi bi-pencil-square edit-icon\"\r\n");
      out.write("											onclick=\"editField('pincode')\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<!-- Update Button -->\r\n");
      out.write("								<button class=\"btn btn-primary\" onclick=\"updateProfile()\">Update</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container mt-5\">\r\n");
      out.write("			<table class=\"table table-bordered\">\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th scope=\"col\">Product name</th>\r\n");
      out.write("						<th scope=\"col\">Description</th>\r\n");
      out.write("						<th scope=\"col\">Price</th>\r\n");
      out.write("						<th scope=\"col\">Actions (Add)</th>\r\n");
      out.write("						<th scope=\"col\">Actions (Buy)</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody id=\"products_container\">\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Payment Modal -->\r\n");
      out.write("		<div class=\"modal fade\" id=\"paymentModal\" tabindex=\"-1\"\r\n");
      out.write("			aria-labelledby=\"paymentModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("			<div class=\"modal-dialog\">\r\n");
      out.write("				<div class=\"modal-content\">\r\n");
      out.write("					<div class=\"modal-header\">\r\n");
      out.write("						<h5 class=\"modal-title\" id=\"paymentModalLabel\">Select Payment\r\n");
      out.write("							Method</h5>\r\n");
      out.write("						<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("							aria-label=\"Close\"></button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-body\">\r\n");
      out.write("						<form id=\"paymentForm\">\r\n");
      out.write("							<div class=\"form-check\">\r\n");
      out.write("								<input class=\"form-check-input\" type=\"radio\"\r\n");
      out.write("									name=\"paymentMethod\" id=\"upi\" value=\"UPI\" checked> <label\r\n");
      out.write("									class=\"form-check-label\" for=\"upi\">UPI</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-check\">\r\n");
      out.write("								<input class=\"form-check-input\" type=\"radio\"\r\n");
      out.write("									name=\"paymentMethod\" id=\"cod\" value=\"COD\"> <label\r\n");
      out.write("									class=\"form-check-label\" for=\"cod\">Cash on Delivery</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("						<p id=\"selectedProduct\"></p>\r\n");
      out.write("						<!-- To display selected product -->\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-footer\">\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("							data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("							onclick=\"submitPayment()\" data-bs-dismiss=\"modal\">Submit</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Change Password Modal -->\r\n");
      out.write("		<div class=\"modal fade\" id=\"changePasswordModal\" tabindex=\"-1\"\r\n");
      out.write("			aria-labelledby=\"changePasswordModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("			<div class=\"modal-dialog\">\r\n");
      out.write("				<div class=\"modal-content\">\r\n");
      out.write("					<div class=\"modal-header\">\r\n");
      out.write("						<h5 class=\"modal-title\" id=\"changePasswordModalLabel\">Change\r\n");
      out.write("							Password</h5>\r\n");
      out.write("						<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("							aria-label=\"Close\"></button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-body\">\r\n");
      out.write("						<form id=\"changePasswordForm\"\r\n");
      out.write("							onsubmit=\"handleChangePassword(event)\">\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<label for=\"newPassword\" class=\"form-label\">Old Password</label>\r\n");
      out.write("								<input type=\"password\" class=\"form-control\" id=\"oldPassword\"\r\n");
      out.write("									required>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<label for=\"newPassword\" class=\"form-label\">New Password</label>\r\n");
      out.write("								<input type=\"password\" class=\"form-control\" id=\"newPassword\"\r\n");
      out.write("									required>\r\n");
      out.write("							</div>\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-primary\"\r\n");
      out.write("								data-bs-dismiss=\"modal\">Submit</button>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("		function editField(field) {\r\n");
      out.write("			document.getElementById(field).disabled = false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		function updateProfileDate(){\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"GET\", \"validator?action=get_user_session\", true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					const data = xhr.responseText;\r\n");
      out.write("					console.log(data);\r\n");
      out.write("					\r\n");
      out.write("					if(!data)\r\n");
      out.write("						return;\r\n");
      out.write("					const userData = data.split(',:');\r\n");
      out.write("					// Update modal fields with the split data\r\n");
      out.write("			        document.getElementById('name').value = userData[0];\r\n");
      out.write("			        document.getElementById('state').value = userData[1];\r\n");
      out.write("			        document.getElementById('city').value = userData[2];\r\n");
      out.write("			        document.getElementById('country').value = userData[3];\r\n");
      out.write("			        document.getElementById('hint').value = userData[4];\r\n");
      out.write("			        document.getElementById('pincode').value = userData[5];\r\n");
      out.write("			        document.getElementById('address').value = userData[6];\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// Function to handle the update (you can connect this to your DB logic here)\r\n");
      out.write("		function updateProfile() {\r\n");
      out.write("			const name = document.getElementById('name').value;\r\n");
      out.write("			const state = document.getElementById('state').value;\r\n");
      out.write("			const city = document.getElementById('city').value;\r\n");
      out.write("			const country = document.getElementById('country').value;\r\n");
      out.write("			const hint = document.getElementById('hint').value;\r\n");
      out.write("			const pincode = document.getElementById('pincode').value;\r\n");
      out.write("			const address = document.getElementById('address').value.trim();\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("			const usernameRegex = /^[A-Za-z][A-Za-z0-9]*$/;\r\n");
      out.write("			if (!usernameRegex.test(name)) {\r\n");
      out.write("				alert(\"name must start with a letter and contain only letters and numbers.\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			const alphaRegex = /^[A-Za-z\\s]+$/;\r\n");
      out.write("			if (!alphaRegex.test(city) || !alphaRegex.test(state)\r\n");
      out.write("					|| !alphaRegex.test(country)) {\r\n");
      out.write("				alert(\"City, State, and Country must contain only letters.\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			if (address.length === 0) {\r\n");
      out.write("				alert(\"Address cannot be empty.\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			if (hint.length === 0) {\r\n");
      out.write("				alert(\"hint cannot be empty.\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			if (isNaN(pincode) || pincode <= 0) {\r\n");
      out.write("				alert(\"Pin Code must be a positive number.\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			const params = new URLSearchParams({\r\n");
      out.write("				action : 'update_profile',\r\n");
      out.write("				userName : name,\r\n");
      out.write("				city : city,\r\n");
      out.write("				state : state,\r\n");
      out.write("				country : country,\r\n");
      out.write("				pincode : pincode,\r\n");
      out.write("				hint : hint,\r\n");
      out.write("				address : address,\r\n");
      out.write("				email : \"e\",\r\n");
      out.write("				phone : \"1\"\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"POST\", \"validator?\" + params.toString(), true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					alert(xhr.responseText);\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		/**\r\n");
      out.write("		method to handle change password\r\n");
      out.write("		 */\r\n");
      out.write("		function handleChangePassword(event) {\r\n");
      out.write("			event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("			const newPassword = document.getElementById('newPassword').value\r\n");
      out.write("					.trim();\r\n");
      out.write("			const oldPassword = document.getElementById('oldPassword').value\r\n");
      out.write("					.trim();\r\n");
      out.write("\r\n");
      out.write("			if (!newPassword || !oldPassword) {\r\n");
      out.write("				alert(\"Please fill all fields\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z]).{8,}$/;\r\n");
      out.write("			if (!passwordRegex.test(newPassword)\r\n");
      out.write("					|| !passwordRegex.test(oldPassword)) {\r\n");
      out.write("				alert(\"Password must be at least 8 characters long, with at least one lowercase and one uppercase letter.\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"POST\", \"validator?action=change_password&newPassword=\"\r\n");
      out.write("					+ newPassword + \"&oldPassword=\" + oldPassword, true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					alert(xhr.responseText);\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("\r\n");
      out.write("			document.getElementById(\"newPassword\").value = '';\r\n");
      out.write("			document.getElementById(\"oldPassword\").value = '';\r\n");
      out.write("		}\r\n");
      out.write("		/**\r\n");
      out.write("		fetch all products \r\n");
      out.write("		 */\r\n");
      out.write("		function fetchAllProducts() {\r\n");
      out.write("\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"GET\", \"products?action=search&query= \", true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					document.getElementById(\"products_container\").innerHTML = xhr.responseText;\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		/**\r\n");
      out.write("		fetch products based on user search\r\n");
      out.write("		 */\r\n");
      out.write("		function fetchProducts(event) {\r\n");
      out.write("			event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("			const formData = new FormData(document\r\n");
      out.write("					.getElementById(\"productForm\"));\r\n");
      out.write("			const params = new URLSearchParams(formData).toString();\r\n");
      out.write("			console.log(params);\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"GET\", \"products?\" + params, true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					document.getElementById(\"products_container\").innerHTML = xhr.responseText;\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		/**\r\n");
      out.write("		method to buy cart items\r\n");
      out.write("		 */\r\n");
      out.write("		function checkout(event) {\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			const selectedPayment = document\r\n");
      out.write("					.querySelector('input[name=\"paymentMethod_checkout\"]:checked').value;\r\n");
      out.write("			xhr.open(\"POST\",\r\n");
      out.write("					\"order_tables_praveen?action=add_order_from_cart&paymentMethod=\"\r\n");
      out.write("							+ selectedPayment, true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					alert(xhr.responseText);\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		/**\r\n");
      out.write("		method to show cart items\r\n");
      out.write("		 */\r\n");
      out.write("		function fetchCartItems(event) {\r\n");
      out.write("			event.preventDefault();\r\n");
      out.write("			const formData = new FormData(document.getElementById(\"cart_form\"));\r\n");
      out.write("			const params = new URLSearchParams(formData).toString();\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("\r\n");
      out.write("			xhr.open(\"GET\", \"cart_item?\" + params, true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					document.getElementById(\"cart_item_container\").innerHTML = xhr.responseText;\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		/**\r\n");
      out.write("		method to create cart\r\n");
      out.write("		 */\r\n");
      out.write("		function create_cart(event) {\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"GET\", \"create_cart\", true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("			console.log(\"create cart\");\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		/**\r\n");
      out.write("		method to add products in cart\r\n");
      out.write("		 */\r\n");
      out.write("		function addToCart(event) {\r\n");
      out.write("			event.preventDefault();\r\n");
      out.write("			const form = event.target;\r\n");
      out.write("			const productId = form.querySelector('input[name=\"productId\"]').value;\r\n");
      out.write("\r\n");
      out.write("			const formData = new FormData(form);\r\n");
      out.write("			const params = new URLSearchParams(formData).toString();\r\n");
      out.write("			console.log(params);\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			console.log(params);\r\n");
      out.write("			xhr.open(\"GET\", \"cart_item?\" + params, true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					document.getElementById(\"cart_item_container\").innerHTML = xhr.responseText;\r\n");
      out.write("					const button = form.querySelector('button'); // Get the button within the form\r\n");
      out.write("\r\n");
      out.write("					// Change the button to a tick icon\r\n");
      out.write("					button.innerHTML = '<i class=\"bi bi-check-circle\"></i>'; // Change to tick icon\r\n");
      out.write("					button.classList.remove('btn-success'); // Remove the success class\r\n");
      out.write("					button.classList.add('btn-info'); // Change to a non-clickable style\r\n");
      out.write("					button.disabled = true;\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("			console.log(\"add to cart\");\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		/**\r\n");
      out.write("		method to clear cart\r\n");
      out.write("		 */\r\n");
      out.write("		function clearCart(event) {\r\n");
      out.write("			event.preventDefault();\r\n");
      out.write("			const formData = new FormData(document\r\n");
      out.write("					.getElementById(\"clear_cart_form\"));\r\n");
      out.write("			const params = new URLSearchParams(formData).toString();\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("\r\n");
      out.write("			xhr.open(\"GET\", \"cart_item?\" + params, true);\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					document.getElementById(\"cart_item_container\").innerHTML = xhr.responseText;\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		/**\r\n");
      out.write("		method to remove cart items\r\n");
      out.write("		 */\r\n");
      out.write("		function deleteItem(button) {\r\n");
      out.write("			const listItem = button.closest('li');\r\n");
      out.write("			const itemId = listItem.getAttribute('data-id'); // Get the item ID\r\n");
      out.write("\r\n");
      out.write("			// Send GET request to the server\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"GET\", \"cart_item?id=\" + itemId\r\n");
      out.write("					+ \"&action=delete_cart_item\", true);\r\n");
      out.write("\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					listItem.remove();\r\n");
      out.write("				} else if (xhr.readyState === 4) {\r\n");
      out.write("					console.error('Failed to delete item:', xhr.status,\r\n");
      out.write("							xhr.statusText);\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("\r\n");
      out.write("			xhr.send(); // Send the request\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		/**\r\n");
      out.write("		method to open payment modal\r\n");
      out.write("		 */\r\n");
      out.write("		function openPaymentModal(button) {\r\n");
      out.write("			const productId = button.getAttribute('data-product-id');\r\n");
      out.write("\r\n");
      out.write("			const modal = document.getElementById('paymentModal');\r\n");
      out.write("			modal.setAttribute('data-product-id', productId);\r\n");
      out.write("			currentBuyButton = button;\r\n");
      out.write("			$('#paymentModal').modal('show');\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		/**\r\n");
      out.write("		method to create order in the order table\r\n");
      out.write("		 */\r\n");
      out.write("		function submitPayment() {\r\n");
      out.write("			const selectedPayment = document\r\n");
      out.write("					.querySelector('input[name=\"paymentMethod\"]:checked').value;\r\n");
      out.write("\r\n");
      out.write("			const modal = document.getElementById('paymentModal');\r\n");
      out.write("			const productId = modal.getAttribute('data-product-id');\r\n");
      out.write("\r\n");
      out.write("			const params = new URLSearchParams({\r\n");
      out.write("				action : \"add_order\",\r\n");
      out.write("				paymentMethod : selectedPayment,\r\n");
      out.write("				productId : productId\r\n");
      out.write("			});\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			console.log(params.toString());\r\n");
      out.write("			xhr.open(\"POST\", \"order_tables_praveen?\" + params.toString(), true);\r\n");
      out.write("\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("					alert(xhr.responseText);\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			xhr.send();\r\n");
      out.write("\r\n");
      out.write("			currentBuyButton.innerHTML = '<i class=\"bi bi-check-circle\"></i>';\r\n");
      out.write("			currentBuyButton.classList.remove('btn-warning');\r\n");
      out.write("			currentBuyButton.classList.add('btn-info');\r\n");
      out.write("			currentBuyButton.disabled = true;\r\n");
      out.write("\r\n");
      out.write("			$('#paymentModal').modal('hide');\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
